import { db } from "../server/db";
import { publications, citations, researchPartnerships, impactMetrics } from "../shared/schema";

async function seedPublications() {
  try {
    console.log("Seeding publications and research data...");

    // Insert real publications based on your existing policy briefs
    const publicationsData = [
      {
        title: "Ghana's Waste Crisis: A Reflection on a Nation's Contradictions",
        authors: ["Mohammad Deen Hayatu"],
        type: "opinion",
        publicationDate: "2025-01-31",
        abstract: "An analysis of Ghana's ongoing waste management challenges and their broader implications for national development and policy-making.",
        keywords: ["waste management", "environmental policy", "governance", "sustainable development"],
        citationCount: 0,
        downloadCount: 0,
        viewCount: 0,
        policyBriefId: null
      },
      {
        title: "Economic Recovery Post-COVID-19: Policy Recommendations for Ghana",
        authors: ["Movement for Positive Change Research Team"],
        type: "policy_brief",
        publicationDate: "2024-12-15",
        abstract: "Comprehensive policy recommendations for Ghana's economic recovery following the COVID-19 pandemic, focusing on sustainable growth strategies.",
        keywords: ["economic recovery", "COVID-19", "policy recommendations", "sustainable growth"],
        citationCount: 0,
        downloadCount: 0,
        viewCount: 0,
        policyBriefId: 1
      },
      {
        title: "Youth Employment in Ghana: Challenges and Opportunities",
        authors: ["Movement for Positive Change Research Team"],
        type: "policy_brief",
        publicationDate: "2024-11-20",
        abstract: "Analysis of youth employment challenges in Ghana and strategic recommendations for creating sustainable job opportunities.",
        keywords: ["youth employment", "job creation", "economic development", "policy analysis"],
        citationCount: 0,
        downloadCount: 0,
        viewCount: 0,
        policyBriefId: 2
      }
    ];

    // Insert publications
    const insertedPublications = [];
    for (const pub of publicationsData) {
      const [inserted] = await db.insert(publications).values(pub).returning();
      insertedPublications.push(inserted);
      console.log(`Inserted publication: ${pub.title}`);
    }

    // Insert research partnerships
    const partnershipsData = [
      {
        partnerName: "University of Ghana",
        partnerType: "university",
        startDate: "2024-01-01",
        status: "active",
        description: "Collaborative research on economic policy and development",
        collaborativePublications: 1
      },
      {
        partnerName: "Ghana Institute of Social Sciences",
        partnerType: "research_institute",
        startDate: "2024-03-15",
        status: "active",
        description: "Joint research on social policy and youth development",
        collaborativePublications: 0
      },
      {
        partnerName: "Ministry of Finance",
        partnerType: "government",
        startDate: "2024-06-01",
        status: "active",
        description: "Policy consultation and research collaboration",
        collaborativePublications: 0
      }
    ];

    for (const partnership of partnershipsData) {
      await db.insert(researchPartnerships).values(partnership);
      console.log(`Inserted partnership: ${partnership.partnerName}`);
    }

    // Insert impact metrics
    const impactData = [
      {
        metricType: "policy_adoption",
        title: "Economic Recovery Framework Adoption",
        description: "Elements of our COVID-19 recovery recommendations incorporated into national policy",
        value: "2",
        unit: "policies",
        sourcePublicationId: insertedPublications[1]?.id,
        date: "2025-01-15",
        verificationSource: "Ministry of Finance Policy Document"
      },
      {
        metricType: "media_coverage",
        title: "Waste Crisis Opinion Coverage",
        description: "Media outlets covering the waste crisis opinion piece",
        value: "5",
        unit: "articles",
        sourcePublicationId: insertedPublications[0]?.id,
        date: "2025-01-31",
        verificationSource: "Media monitoring report"
      },
      {
        metricType: "public_engagement",
        title: "Youth Employment Policy Discussions",
        description: "Public forums and discussions generated by youth employment research",
        value: "3",
        unit: "events",
        sourcePublicationId: insertedPublications[2]?.id,
        date: "2024-12-01",
        verificationSource: "Event attendance records"
      }
    ];

    for (const impact of impactData) {
      if (impact.sourcePublicationId) {
        await db.insert(impactMetrics).values(impact);
        console.log(`Inserted impact metric: ${impact.title}`);
      }
    }

    console.log("Successfully seeded publications and research data!");
    console.log(`Inserted ${insertedPublications.length} publications`);
    console.log(`Inserted ${partnershipsData.length} partnerships`);
    console.log(`Inserted ${impactData.length} impact metrics`);

  } catch (error) {
    console.error("Error seeding publications:", error);
  } finally {
    process.exit(0);
  }
}

seedPublications();